// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Listing struct {
	ID         int64
	Body       string
	IsHidden   bool
	HiddenAt   sql.NullTime
	CreatedAt  time.Time
	IpHash     []byte
	BodyLength sql.NullInt32
	HasLinks   sql.NullBool
	LinkCount  sql.NullInt32
	BodyTsv    interface{}
}
